version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - type: volume
        source: postgresdb-data1
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bmstu_user
      POSTGRES_DB: bmstu
      POSTGRES_PASSWORD: bmstu_password

volumes:
  postgresdb-data1:
    driver: local
