# Generated by Django 4.1.1 on 2022-10-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_bmstu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="range", name="name",),
        migrations.AddField(
            model_name="client",
            name="login",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="range",
            name="rangeName",
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="number_card",
            field=models.IntegerField(
                blank=True, default=None, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(default=None, max_length=11),
        ),
    ]
