# Generated by Django 4.1.1 on 2022-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_bmstu", "0002_remove_range_name_client_login_client_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="number_card",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
