# Generated by Django 4.1.1 on 2022-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_bmstu", "0003_alter_client_number_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
