# Generated by Django 4.1.1 on 2022-10-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab_bmstu", "0004_alter_client_password"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="login",),
        migrations.RemoveField(model_name="client", name="password",),
    ]
