# Generated by Django 4.1.1 on 2022-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_bmstu", "0005_remove_client_login_remove_client_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="login",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
